### ISSUE TITLE
Plugin license

### ISSUE THREAD

**Issue by onetruebob** [DispatchMe/phoneformat.js#24]
I can't seem to find the license that applies to using this plugin. I know the underlying Google libphonenumber has an Apache license.

https://github.com/googlei18n/libphonenumber/blob/master/LICENSE

Would you want to include that license here too?

Thanks for the great work.

**Comment by jperl** [comment]
It's MIT, added it to the readme. Sorry for the delay.

**Comment by onetruebob** [comment]
Good deal. Thank you.
